Name: GalacticExpansion
Description: Dynamic Zirax colony evolution and intelligent threat response system
Author: Gexon
Version: 1.0.0-alpha1
Website: https://github.com/Gexon/GalacticExpansion

# Mod works on dedicated server and playfield server
ModTargets: Dedi
